(function(){function o(a){typeof a=="string"&&(a=g.getElementById(a));return a}function j(a,b,d){k.addEventListener?a.addEventListener(b,d,!1):k.attachEvent&&a.attachEvent("on"+b,function(){d.call(a,k.event)})}function l(a,b){a.className=a.className.replace(RegExp("(\\s|^)"+b+"(\\s|$)")," ")}var g=document,k=window,m=function(){var a=g.createElement("div");return function(b){a.innerHTML=b;b=a.childNodes[0];a.removeChild(b);return b}}(),n=document.documentElement.getBoundingClientRect?function(a){var b=
a.getBoundingClientRect(),d=a.ownerDocument,a=d.body,d=d.documentElement,f=d.clientTop||a.clientTop||0,c=d.clientLeft||a.clientLeft||0,e=1;a.getBoundingClientRect&&(e=a.getBoundingClientRect(),e=(e.right-e.left)/a.clientWidth);e>1&&(c=f=0);return{top:b.top/e+(window.pageYOffset||d&&d.scrollTop/e||a.scrollTop/e)-f,left:b.left/e+(window.pageXOffset||d&&d.scrollLeft/e||a.scrollLeft/e)-c}}:function(a){if(k.jQuery)return jQuery(a).offset();var b=0,d=0;do b+=a.offsetTop||0,d+=a.offsetLeft||0;while(a=a.offsetParent);
return{left:d,top:b}},p=function(){var a=0;return function(){return"ValumsAjaxUpload"+a++}}();Ajax_upload=AjaxUpload=function(a,b){a.jquery?a=a[0]:typeof a=="string"&&/^#.*/.test(a)&&(a=a.slice(1));a=o(a);this._input=null;this._button=a;this._justClicked=this._submitting=this._disabled=!1;this._parentDialog=g.body;if(window.jQuery&&jQuery.ui&&jQuery.ui.dialog){var d=jQuery(this._button).parents(".ui-dialog");if(d.length)this._parentDialog=d[0]}this._settings={action:"upload.php",name:"userfile",data:{},
autoSubmit:!0,responseType:!1,onChange:function(){},onSubmit:function(){},onComplete:function(){}};for(var f in b)this._settings[f]=b[f];this._createInput();this._rerouteClicks()};AjaxUpload.prototype={setData:function(a){this._settings.data=a},disable:function(){this._disabled=!0},enable:function(){this._disabled=!1},destroy:function(){if(this._input)this._input.parentNode&&this._input.parentNode.removeChild(this._input),this._input=null},_createInput:function(){var a=this,b=g.createElement("input");
b.setAttribute("type","file");b.setAttribute("name",this._settings.name);var d={position:"absolute",margin:"-5px 0 0 -175px",padding:0,width:"220px",height:"30px",fontSize:"14px",opacity:0,cursor:"pointer",display:"none",zIndex:2147483583},f;for(f in d)b.style[f]=d[f];if(b.style.opacity!=="0")b.style.filter="alpha(opacity=0)";this._parentDialog.appendChild(b);j(b,"change",function(){var b=this.value.replace(/.*(\/|\\)/,"");a._settings.onChange.call(a,b,/[.]/.exec(b)?/[^.]+$/.exec(b.toLowerCase()):
"")!=!1&&a._settings.autoSubmit&&a.submit()});j(b,"click",function(){a.justClicked=!0;setTimeout(function(){a.justClicked=!1},3E3)});this._input=b},_rerouteClicks:function(){var a=this,b,d={top:0,left:0},f=!1;j(a._button,"mouseover",function(){if(a._input&&!f){f=!0;var c=a._button,e,h;h=n(c);e=h.left;h=h.top;b={left:e,right:e+c.offsetWidth,top:h,bottom:h+c.offsetHeight};a._parentDialog!=g.body&&(d=n(a._parentDialog))}});j(document,"mousemove",function(c){var e=a._input;if(e&&f)if(a._disabled)l(a._button,
"hover"),e.style.display="none";else{if(!c.pageX&&c.clientX){var h=1,i=document.body;i.getBoundingClientRect&&(h=i.getBoundingClientRect(),h=(h.right-h.left)/i.clientWidth);c={x:c.clientX/h+g.body.scrollLeft+g.documentElement.scrollLeft,y:c.clientY/h+g.body.scrollTop+g.documentElement.scrollTop}}else c={x:c.pageX,y:c.pageY};if(c.x>=b.left&&c.x<=b.right&&c.y>=b.top&&c.y<=b.bottom)e.style.top=c.y-d.top+"px",e.style.left=c.x-d.left+"px",e.style.display="block",e=a._button,e.className.match(/(\s|^)hover(\s|$)/)||
(e.className+=" hover");else{f=!1;if(!a.justClicked)e.style.display="none";l(a._button,"hover")}}})},_createIframe:function(){var a=p(),b=m('<iframe src="javascript:false;" name="'+a+'" />');b.id=a;b.style.display="none";g.body.appendChild(b);return b},submit:function(){var a=this,b=this._settings;if(this._input.value!==""){var d=this._input.value.replace(/.*(\/|\\)/,"");if(b.onSubmit.call(this,d,/[.]/.exec(d)?/[^.]+$/.exec(d.toLowerCase()):"")!=!1){var f=this._createIframe(),c=this._createForm(f);
c.appendChild(this._input);c.submit();g.body.removeChild(c);this._input=c=null;this._createInput();var e=!1;j(f,"load",function(){if(f.src=="javascript:'%3Chtml%3E%3C/html%3E';"||f.src=="javascript:'<html></html>';")e&&setTimeout(function(){g.body.removeChild(f)},0);else{var c=f.contentDocument?f.contentDocument:frames[f.id].document;if(!(c.readyState&&c.readyState!="complete")&&!(c.body&&c.body.innerHTML=="false")){var i;if(c.XMLDocument)i=c.XMLDocument;else if(c.body){if(i=c.body.innerHTML,b.responseType&&
b.responseType.toLowerCase()=="json"){if(c.body.firstChild&&c.body.firstChild.nodeName.toUpperCase()=="PRE")i=c.body.firstChild.firstChild.nodeValue;i=i?window.eval("("+i+")"):{}}}else i=c;b.onComplete.call(a,d,i);e=!0;f.src="javascript:'<html></html>';"}}})}else g.body.removeChild(this._input),this._input=null,this._createInput()}},_createForm:function(a){var b=this._settings,d=m('<form method="post" enctype="multipart/form-data"></form>');d.style.display="none";d.action=b.action;d.target=a.name;
g.body.appendChild(d);for(var f in b.data)a=g.createElement("input"),a.type="hidden",a.name=f,a.value=b.data[f],d.appendChild(a);return d}}})();
